### ISSUE TITLE
Deployment not working 

### ISSUE THREAD

**Issue by abaidgulshan** [Prashanna313/AWS_Lambda_with_K8s#1]
@Prashanna313 Your mentioned flow works for me and I got 200 status but I am getting` [Errno 2] No such file or directory: 'aws': 'aws' `and deployment never happens. Any idea if I am missing anything 
![Screenshot (22)](https://user-images.githubusercontent.com/7329596/102559207-1ba49900-40f1-11eb-9cfd-3c24c79d6e6b.png)

**Comment by Prashanna313** [comment]
Since .kubeconfig file is not present locally this lambda will try to create it by running the relevant AWS commands. It's where you're getting this error

**Comment by abaidgulshan** [comment]
> Since .kubeconfig file is not present locally this lambda will try to create it by running the relevant AWS commands. It's where you're getting this error

@Prashanna313  Yes I saw that in code and try to print config file on lambda run time after it create and this is result I am getting. Let me know if that config looks OK
```
Kind: config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXXX
    server: https://XXXXXX.gr7.us-east-1.eks.amazonaws.com
  name: EKS-CLUSTER
contexts:
- context:
    cluster: EKS-CLUSTER
    user: arn:aws:eks:us-east-1:XXXXXX:cluster/EKS-CLUSTER
  name: arn:aws:eks:us-east-1:XXXXXX:cluster/EKS-CLUSTER
current-context: arn:aws:eks:us-east-1:XXXXXX:cluster/EKS-CLUSTER
users:
- name: arn:aws:eks:us-east-1:XXXXXX:cluster/EKS-CLUSTER
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - EKS-CLUSTER
      command: aws
